version: "3.7"
services:
  users-service:
    build: "./users-service"
    ports:
      - 3001:3000
    depends_on: 
      - db-postgres
    environment:
      DATABASE_URL: postgres://root:password@db-postgres:5432/mainDB

  posts-service:
    build: "./posts-service"
    ports:
      - 3002:3000
    depends_on: 
      - db-mongo
    environment: 
      MONGO_URL: mongodb://root:password@db-mongo:27017/service

  theards-service:
    build: "./theards-service"
    ports:
      - 3003:3000
  
  db-postgres:
    image: postgres:12.7-alpine
    ports: 
      - 5432:5432
    environment: 
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "mainDB"
    volumes: 
      - db-postgres:/var/lib/postgresql/data
  
  db-mongo:
    image: mongo
    ports: 
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "password"
    volumes: 
      - db-mongo:/data/db

  mongo-express:
    image: mongo-express
    ports:
      - 27000:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: "db-mongo"
      ME_CONFIG_MONGODB_ADMINUSERNAME: "root"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "password"

volumes: 
  db-postgres:
  db-mongo:


